name: Tests and checks

on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test coverage
        run: |
          PYTHONPATH=src python -m coverage run -m unittest discover -v fk.tests
          python -m coverage html
      - name: Archive code coverage results 
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
