name: Release new version

on:
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test coverage
        run: |
          PYTHONPATH=src python -m coverage run -m unittest discover -v fk.tests
          python -m coverage html
      - name: Archive code coverage results 
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov

  package-linux:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Package the build
        run: |
          pyinstaller desktop.spec
          mv dist/desktop dist/flowkeeper-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/flowkeeper-linux
          
  package-windows:
    runs-on: windows-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Package the build
        run: |
          pyinstaller desktop.spec
          move dist\desktop.exe dist\Flowkeeper.exe
      - name: Download innosetup installer
        run: |
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
      - name: Install innosetup
        shell: cmd
        run: |
          start /wait innosetup.exe /VERYSILENT /CURRENTUSER /SUPPRESSMSGBOXES /NOICONS
      - name: Create FK installer
        shell: cmd
        run: |
          start /wait "%USERPROFILE%\AppData\Local\Programs\Inno Setup 6\ISCC.exe" desktop.iss
          move Output\mysetup.exe dist\setup.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/Flowkeeper.exe
            dist/setup.exe

  package-macOS:
    runs-on: macOS-latest
    if:  ${{ inputs.OS == 'macOS' }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          brew install create-dmg
      - name: Package the build
        run: |
          pyinstaller desktop.spec
      - name: Create DMG installer
        run: |
          rm dist/desktop
          mv dist/desktop.app dist/Flowkeeper.app
          create-dmg \
            --volname "Flowkeeper Installer" \
            --volicon "res/flowkeeper.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Flowkeeper.app" 200 190 \
            --hide-extension "Flowkeeper.app" \
            --app-drop-link 600 185 \
            "Flowkeeper.dmg" \
            "dist/"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Flowkeeper.dmg
