name: Test innosetup

on:
  workflow_dispatch:
jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - name: Download innosetup installer
        run: |
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
      - name: Run the installer
        shell: cmd
        run: |
          dir
          start /wait innosetup.exe /VERYSILENT /CURRENTUSER /SUPPRESSMSGBOXES /NOICONS
