name: Test innosetup

on:
  workflow_dispatch:
jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - name: Create installer
        run: |
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT /CURRENTUSER /SUPPRESSMSGBOXES /NOICONS" -Wait
